x = 10
print("The type of x is:", type(x))
y = float(x)
print("The type of y is:", type(y))
z = str(x)
print("The type of z is:", type(z))
a = "123"
print("The type of a is:", type(a))
b = int(a)
print("The type of b is:", type(b))
c = float(a)
print("The type of c is:", type(c))
d = 12.5
print("The type of d is:", type(d))
e = int(d)
print("The type of e is:", type(e))
f = str(d)
print("The type of f is:", type(f))
g = "hello"
print("The type of g is:", type(g))
# h = int(g) # This will cause an error
# print("The type of h is:", type(h))
# i = float(g) # This will cause an error
# print("The type of i is:", type(i))
# j = complex(g) # This will cause an error
# print("The type of j is:", type(j))
k = complex(x)
print("The type of k is:", type(k))
l = bool(x)
print("The type of l is:", type(l))
m = bool(0)
print("The type of m is:", type(m))
n = bool("")
print("The type of n is:", type(n))
o = bool("hello")
print("The type of o is:", type(o))
p = list("hello")
print("The type of p is:", type(p))
print("The value of p is:", p)
q = tuple("hello")
print("The type of q is:", type(q))
print("The value of q is:", q)
r = set("hello")
print("The type of r is:", type(r))
print("The value of r is:", r)
s = dict([('a', 1), ('b', 2)])
print("The type of s is:", type(s))
print("The value of s is:", s)
